title: Stampa 3D Manduria
email: free3dmakers@gmail.com
description: Soluzioni, cambiamenti e azioni: sono questi i nostri credo per rispondere all’emergenza COVID-19, e noi lo facciamo concretamente. Siamo un team di makers volontari che produce e dona valvole e visiere in 3D. Perché la beneficenza è attivismo!
theme: minima
plugins:
  - jekyll-feed
